filebeat.inputs:
  - type: log
    id: ssh-auth
    enabled: true
    paths:
      - /var/log/auth.log
    fields:
      log_type: ssh_auth
    fields_under_root: true

output.logstash:
  hosts: ["logstash:5044"]

setup.kibana:
  host: "kibana:5601"