{
 "title": "Authentication Security Overview",
 "description": "Security dashboard for authentication telemetry",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Auth Events",
   "type": "timeseries",
   "description": "Distribution of auth_status over time",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "auth_status.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Successed Auth Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "auth_status.keyword:\"success\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Failed Auth Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "auth_status.keyword:\"failure\"",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}